### ISSUE TITLE
Parent as link with Next Button

### ISSUE THREAD

**Issue by cbaone** [codrops/ResponsiveMultiLevelMenu#28]
Has anyone had use for, or implemented a change to the menu where only the arrows advance the menu, but the links still work? I've got a menu that needs parents as links. So, basically, each item on the menu takes you to a page unless you click the button (which will advance to next level).

I know there is the: useActiveItemAsLink: true, config, but that still requires the user to click once more to get to that item and it's not very intuitive. Is there simple way to do: useParentItemAsLink: true ? By maybe appending a clickable arrow on each link that has children?

I'm just thinking about this right now, but I'm not entirely sure how to implement it:

```
        if (this.options.useParentItemAsLink) {
            this.$el.find( 'ul.dl-submenu li' ).append(function() {
                var parentlink = $(this).parents('li:not(.dl-back)').find('a');
                return '<span class="chevron-right"></span>';
            });
        }
```

I realize that would have to become the new trigger, but not exactly sure how to proceed. Any thoughts?

Thanks!

**Comment by egillah** [comment]
I am trying to do the same. Anyone done this ?

**Comment by HermanTk** [comment]
I've done this by changing slightly a menu structure: added span with expand class after /a tag but before ul class="dl-submenu" tag. 
Than I've rewrited dlmenu.js changing part on('click.dl-menu', function(event){}), which describes behavior of menu when clicking on it.
As a result I've got span which opens next level and a which goes to particular page.

**Comment by egillah** [comment]
herrDOS: Do you have a live demo ? would be very heplfull :)

**Comment by mickcastle** [comment]
Yeah I'm wondering the same
