### ISSUE TITLE
How can I make the parent link clickable?

### ISSUE THREAD

**Issue by TrangDinhVan** [codrops/ResponsiveMultiLevelMenu#32]
Is there any way say I can go to the URL of the parent link item. You know, now when I click on a parent link, it will open the sub menu, so I cannot go to the URL of parent link.
I tried to add the parent link to its sub menu but when I click it, it still just open the sub menu.

**Comment by sander-lameco** [comment]
Did you find a fix? I'm looking for the answer on the same question.
